frontend/src/App.jsx, frontend/src/assets/Components/Login/Signup.css, frontend/src/assets/Components/Login/Signup.jsx
I made a signup page which user  can use for signing up. I resolved #5 .
=> Signup component

frontend/src/App.css, frontend/src/App.jsx, frontend/src/assets/Components/Footer/Footer.css, frontend/src/assets/Components/Footer/Footer.jsx, frontend/src/assets/Components/Login/Signup.css, frontend/src/assets/Components/Login/Signup.jsx, frontend/src/assets/Components/Navbar/Navbar.css
i fix the colour theme for the LinkUp.ai #14  #F9FAFB (ghost white), #111827 (charcoal gray), and #EEF2FF (lavender mist).
these give the perfect balance. clean, modern, and very student-friendly.
#F9FAFB works really well as a soft background, #111827 is perfect for text or dark sections like the footer
and #EEF2FF adds a little freshness — good for cards or highlighted sections without being too loud.
i feel this combo keeps the UI minimal and still gives that smart, premium feel.
Also fixed a small issue in the signup form changed the input type from number to tel for better mobile UX and formatting.
=> Fix the colour theme for the LinkUp.AI #14

frontend/src/assets/Components/Login/Signup.css, frontend/src/assets/Components/Login/Signup.jsx, frontend/src/assets/Components/Navbar/Navbar.css, frontend/src/assets/Components/Navbar/Navbar.jsx
description:
* Fixed the issue #17  with the placement of the search bar
* Increased the size of the Sign Up button and add small effects when click
* Increased the size of the logo slightly
* Renamed the "Project Summary" section to "Career Boost"
=> Fix the placement of searchbar 

frontend/package-lock.json, frontend/package.json, frontend/src/App.jsx, frontend/src/assets/Components/Navbar/Navbar.css, frontend/src/assets/Components/Navbar/Navbar.jsx, frontend/src/assets/Components/Profile/Profile.css, frontend/src/assets/Components/Profile/Profile.jsx
**What I did:**
- Created a dedicated Profile page containing multiple sections:
1. Personal Information
2. Social Links
3. Skills & Documents
4. Projects
5. Education
6. Experience & Achievements
7. Final Review
- Designed the layout to guide the user step-by-step through profile completion.
- Implemented routing so that clicking on "Profile" in the Navbar navigates to this new Profile page.
- Ensured modular structure for future scalability and easier integration with backend/user data.
- Solved issue #22
=> Created the profile page 

frontend/src/assets/Components/Internships/Internships.css, frontend/src/assets/Components/Internships/Internships.jsx
Made the internship page where users can search about their domain specific internships.
This section also has quotes that inspires users to do more and more internships.
Worked on #21
=> Internship Component

frontend/src/App.jsx, frontend/src/assets/Components/CareerBoost/CareerBoost.css, frontend/src/assets/Components/CareerBoost/CareerBoost.jsx, frontend/src/assets/Components/Navbar/Navbar.css, frontend/src/assets/Components/Navbar/Navbar.jsx, frontend/src/assets/Components/hackathon/Hackathon.jsx, frontend/src/assets/Components/hackathon/Hackathonstyle.css
Career Boost Feature Added #43
• Added a new Career Boost page to suggest certificates based on searched roles.
• Integrated role-based certificate data with images (Frontend, Backend, UI/UX, etc.).
• Connected Career Boost from Navbar → AI Assist dropdown.
• Styled with external CareerBoost.css for responsive layout and clean UI.
• Minor UI fixes: Added top margin to footer logos for better spacing.
=> Added careerboost page

frontend/src/assets/Components/Jobs/Jobs 2.css, frontend/src/assets/Components/hackathon/Hackathon.jsx, frontend/src/assets/Components/hackathon/Hackathonstyle.css
solved issue #61 
i have erased extra text .
=> erased extra text

frontend/src/App.jsx, frontend/src/assets/Components/Navbar/Navbar.jsx
solved issue #50 
i have fixed the working of home when sign in.
=> fixe home when sign in

frontend/src/App.jsx, frontend/src/assets/Components/home_content/Homecontent.css, frontend/src/assets/Components/home_content/Homecontent.jsx, frontend/src/assets/Components/home_content/TechNewsCard.css, frontend/src/assets/Components/home_content/TechNewsCard.jsx
**What I did:**
- Solved issue #55
- Enhanced the Home page with animations for a smoother and more engaging user experience.
- Added "What is LinkUp.AI" and "Features" sections with scroll-based appearance effects.
- Moved the News section to the bottom of the Home page to create a more natural content flow.
- Connected the "Start building your profile" button to redirect users to the Signup page.
=> Enhanced Home page

frontend/src/assets/Components/hackathon/Hackathon.jsx, frontend/src/assets/Components/hackathon/Hackathonstyle.css
This PR delivers a complete revamp of the Hackathon page UI and functionality as outlined in **Issue #76**. The previous version had static elements and minimal interactivity. The new version introduces a modern layout, responsive cards, animations, working search, filter buttons, and section scroll — elevating the UX significantly.
---
- Static image banner with no interaction
- Basic image tiles for 3 hackathons
- Hardcoded images and titles
- Non-functional search bar and no filters
- No categorization or sorting
---
- 🖼️ Hero section with animated background and smooth fade-in transitions
- 🔍 Fully working search bar (search by name or tags)
- 🧩 Functional filter buttons (e.g., Blockchain, AI, Web3)
- 🪄 Responsive and animated hackathon cards with metadata
- 📍 "Browse All Events" …
=> Improve Hackathon Page UI (Closes Issue #76)

frontend/src/App.css, frontend/src/assets/Components/BioGenerator/BioGenerator.css, frontend/src/assets/Components/BioGenerator/BioGenerator.jsx
•added gradient background and hover effect in the top section to make it look better #70 
•updated buttons with proper padding and smooth hover animations
•made the bio output box cleaner and more readable with soft colors and rounded corners
=> Improve bio generator UI and animation

frontend/src/App.jsx, frontend/src/assets/Components/Navbar/Navbar.jsx, frontend/src/assets/Components/Profile/Profile.jsx, frontend/src/assets/Components/ResumeBuilder/ResumeBuilder.css, frontend/src/assets/Components/ResumeBuilder/ResumeBuilder.jsx
I have worked on #59 . Please review it
=> Resume Builder

frontend/src/assets/Components/Login/Login.css, frontend/src/assets/Components/Login/Login.jsx, frontend/src/assets/Components/Login/Signup.css, frontend/src/assets/Components/Login/Signup.jsx
- I have resolved the issue #74 . Please review
=> Updated Login and Signup components

frontend/package-lock.json, frontend/package.json, frontend/src/assets/Components/ResumeBuilder/ResumeBuilder.jsx
solved issue #80 
i have converted the download of resume from latex type to pdf
=> converted latex to pdf type of resume

frontend/src/App.jsx, frontend/src/assets/Components/Post/Post.css, frontend/src/assets/Components/Post/Post.jsx, frontend/src/assets/Components/Profile/Profile.jsx
**What I did:**
- Solved issue #84 
- Created a "Create Post" UI inspired by LinkedIn, allowing users to:
- Write a professional post (up to 3000 characters)
- Add photos, emojis, location, and hashtags
- Built a Recent Posts feed UI with:
- Profile info, post content, timestamp, and location
- Like and comment section
- Added styling via Post.css for responsive and modern layout
- Implemented a comment box under each post to allow interaction
=> Made the post section of the website

frontend/package-lock.json, frontend/src/assets/Components/CareerBoost/CareerBoost.css, frontend/src/assets/Components/CareerBoost/CareerBoost.jsx
I have fixed the UI of career boost section. #94
=> Career Boost Ui enhancement

frontend/package-lock.json, frontend/package.json, frontend/src/assets/Components/Profile/Profile.css, frontend/src/assets/Components/Profile/Profile.jsx
=> Fixed the next and previous button alignment in the profile section

frontend/src/assets/Components/Footer/Footer.css, frontend/src/assets/Components/Footer/Footer.jsx, frontend/src/assets/Components/home_content/Homecontent.jsx
solved #89 issue
i have edited some link and made it working.
=> working footer

Backend/server.js, frontend/src/assets/Components/Chat/Chat.jsx
This was just the server setup for private mesaging.
Working on #141 .
=> Setting up server for the private messaging.

frontend/package-lock.json, frontend/package.json, frontend/src/assets/Components/Profile/Profile.css, frontend/src/assets/Components/Profile/Profile.jsx, frontend/src/assets/Components/Profile/UploadProgress.css, frontend/src/assets/Components/Profile/UploadProgress.jsx, frontend/src/utils/cloudinary-config.js, frontend/src/utils/cloudinary.js, frontend/src/utils/firestore-helpers.js
solved issue #131 
stored photos and doc in cloudinary and posted url to firebase firestore
=> profile data

Backend/server.js, frontend/src/assets/Components/Chat/Chat.jsx
I have worked on the issue #157 . 
Initially the code used localhost url's for the chatting purpose but now it will use the deployed url.
@ananyapandey9895 please review and merge.
=> Configuration of private messaging

Backend/server.js
some minor changes for backend.
=> changes for backend
